version: '2'

pipeline:
  # laravel for the backend
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./taskapp:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    commands:
      - php vendor/bin/phpunit
    branches: [ master, staging ]

  # vuejs for the frontend
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8090:80
    # commands:
    #   - npm run lint
    # branches: [ master staging ]

services:
  # mysql for persistence
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:

#   notify:
#     image: plugins/slack
#     channel: developers
#     username: drone
#     when:
#       status: [ success, failure ]
