pipeline:
  buildapp:
    image: michalpodeszwa/docker-compose:latest
    group: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      # rebuild the environment to make sure nothing broke (i.e., test for docker config changes)
      # - docker-compose -f taskapp.docker-compose.yml up -d --build
      - docker-compose -f taskapp.docker-compose.yml up -d
      ## - until docker info >/dev/null 2>&1; do echo "Waiting for internal docker.." sleep 1 done
    # when:
    #   event: [pull_request]

  installdeps:
    # cleanup house
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd taskapp && docker run --rm -v $(pwd):/app library/composer install && cd ..

  test:
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      # all this jazz because I can't figure out how to map the source folder in the container :()
      # not sure why it doesn't work with this image (works on local just fine...)
      # TODO: maybe use the rsync plugin for speedup?
      #       or figure out how to map the volume correctly
      - docker-compose -f taskapp.docker-compose.yml exec -T app rm -rf /var/www/*
      - docker cp taskapp/. $(docker ps | grep '_app' | cut -d \  -f 1):/var/www
      - docker-compose -f taskapp.docker-compose.yml exec -T app ls -l
      - docker-compose -f taskapp.docker-compose.yml exec -T app php vendor/bin/phpunit
    # when:
    #   event: [pull_request]

  teardown:
    # cleanup house
    image: michalpodeszwa/docker-compose:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker-compose -f taskapp.docker-compose.yml down
    when:
      # always cleanup
      status: [success, failure]

  # pipeline:
  #   slack:
  #     image: plugins/slack
  #     channel: dev
  #     when:
  #       status: [ success, failure ]
